### ISSUE TITLE
Roadmap to reading emails

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/aerc#51]
I want to do the following things before we start trying to read emails:
- [x] STARTTLS (#36)
- [ ] Fix bugs with switching mailboxes too fast
- [ ] IMAP SORT (#48)
- [ ] Subject line printing (#22)
- [x] :set (#50)
- [ ] Handle emails being deleted by other clients (#49)
